[env]
LIBSQLITE3_FLAGS = "-DSQLITE_OS_OTHER=1 -DSQLITE_TEMP_STORE=3 -USQLITE_THREADSAFE -DSQLITE_THREADSAFE=1 -DSQLITE_OMIT_WAL -DSQLITE_MAX_MMAP_SIZE=0 -USQLITE_USE_URI -USQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_OMIT_LOAD_EXTENSION"
CPATH = { value = "third_party/vita_sqlite_compat", relative = true }
